dashboard/product/urls.py
from django.urls import path
from . import views
from dashboard.decorators import user_dashboard_permissions

app_name = 'product_dashboard'

urlpatterns = [
    path('create/', user_dashboard_permissions(views.CreateProduct.as_view()), name='product_create'),
    path('list/', user_dashboard_permissions(views.ProductList.as_view()), name='product_list'),
    path('update/<int:pk>/', user_dashboard_permissions(views.UpdateProduct.as_view()), name='product_update'),
    path('<int:pk>/list/images/', user_dashboard_permissions(views.ProductImageList.as_view()), name='product_image_list'),
    path('<int:pk>/create/image/', user_dashboard_permissions(views.create_image), name='create_image'),
    path('delete/image/<int:pk>/', user_dashboard_permissions(views.delete_image), name='delete_image'),
    path('delete/<int:pk>/', user_dashboard_permissions(views.delete_product), name='delete_product'),
    
]

groceryshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('product.urls', namespace='products')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('order/', include('order.urls', namespace='order')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


    
    

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('<int:pk>/', views.DetailOrder.as_view(), name='detail_order'),
    path('', views.ListOrder.as_view(), name='list_order'),
   
]

product/urls.py
from  django.urls import path
from product import views

app_name = 'products'

urlpatterns = [
    path('<str:slug>/', views.detail_product, name='detail_product'),
    path('category/<str:slug>/', views.ListProduct.as_view(), name='list_product'),
    path('add/<int:pk>/', views.add_product_to_checkout, name='add_product_to_checkout')
]

product/models.py
from django.db import models
from django.urls import reverse_lazy
from mptt.models import MPTTModel
from mptt.managers import TreeManager

# Create your models here.
class Category(MPTTModel):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    background_image = models.ImageField(null=True, blank=True, upload_to='category_background')
    

    tree = TreeManager()
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("dashboard:category_dashboard:category_list")

   
    
    

class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField()

    def get_absolute_url(self):
        return reverse_lazy("dashboard:brand_dashboard:brand_list")
    
    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField()
    weight = models.FloatField()
    sku = models.CharField(max_length=30, unique=True)
    stock = models.PositiveIntegerField()
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse_lazy("dashboard:product_dashboard:product_list")
    
    def get_thumbnail(self):
        return self.productimage_set.first()

class ProductImage(models.Model):
    image = models.ImageField()
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    alt = models.CharField(max_length=255)

    def __str__(self):
        return self.alt
    

dashboard/product/forms.py
from django import forms

from product.models import ProductImage


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        exclude = ('product','alt', )

dashboard/product/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import CreateView, UpdateView,ListView
from django.utils.text import slugify
from dashboard.product.forms import ProductImageForm
from product.models import Product, ProductImage
from django.http import JsonResponse
# Create your views here.





class CreateProduct(CreateView):
    model= Product
    fields = ['name', 'description', 'sku', 'price', 'brand', 'stock', 'category', 'weight' ]
    template_name = 'dashboard/product/create.html'

    def form_valid(self, form):
        instance = form.save()
        instance.slug = slugify(instance.name) + "-" + str(instance.id)
        instance.save()
        return super(CreateProduct, self).form_valid(form)




class UpdateProduct(UpdateView):
    model= Product
    fields = ['name', 'category', 'description', 'sku', 'price', 'brand','weight', ]
    template_name = 'dashboard/product/create.html'

    def form_valid(self, form):
        instance = form.instance
        instance.slug = slugify(instance.name) + "-" + str(instance.id)
        instance.save()
        return super(UpdateProduct, self).form_valid(form)
    

class ProductList(ListView):
    model = Product
    template_name = 'dashboard/product/list.html'

class ProductImageList(ListView):
    model = ProductImage
    template_name = 'dashboard/product/list_image.html'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductImageList, self).get_context_data(**kwargs)
        context["form"] = ProductImageForm()
        context["product_id"] = self.kwargs.get('pk') 
        return context
    
    def get_queryset(self):
        return super(ProductImageList, self).get_queryset().filter(product__id = self.kwargs.get('pk'))
    

def create_image(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = ProductImageForm(request.POST, request.FILES)
    print(form)
    
    if form.is_valid():
        image_obj = form.save(commit=False)
        image_obj.product = product
        image_obj.alt = product.name
        image_obj.save()
        return JsonResponse({
                'message': 'Product image created successfully', 
                'url': image_obj.image.url,
                'alt': image_obj.alt,
                'delete_url': reverse('dashboard:product_dashboard:delete_image', kwargs={
                'pk': image_obj.id,
                    })},
                status=200)
    return JsonResponse({'error':'Failed to create product image', 'errors': form.errors}, status=400)
  

def delete_image(request, pk):
    product_image = get_object_or_404(ProductImage, pk=pk)
    if product_image:
        product_image.delete()
        return JsonResponse({'message': 'Product image deleted successfully'}, status=200)
    return JsonResponse({'message':'this product image instance does not exist'}, status=400)


def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product:
        product.delete()
        return JsonResponse({'message': 'Product  deleted successfully'}, status=200)
    return JsonResponse({'message':'this product  instance does not exist'}, status=400)

product/views.py
from datetime import timedelta
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView,DetailView
from product.models import Product, Category
from  checkout.forms import CheckOutLineForm
from checkout.models import Checkout, CheckoutLine

def detail_product(request, slug, form=None):
    product = get_object_or_404(Product, slug=slug)
    if not form:
        form = CheckOutLineForm(request.POST or None, product=product)
    context = {
        'object': product,
        'form': form,
    }
    return render(request, 'product/detail.html', context)


class ListProduct(ListView):
    model = Product
    template_name = 'product/list.html'
    paginate_by = 1

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        categories = category.get_descendants(include_self=True)
        qs = super(ListProduct, self).get_queryset().filter(
            category__in = categories
        )
        return qs

def get_or_create_checkout(request,  checkout_queryset = Checkout.objects.all()):
   user = request.user
   if request.user.is_authenticated:
       
       return checkout_queryset.get_or_create(
           user = user,
           email = request.user.email 
       )[0]
   token = request.get_signed_cookie('checkout', default=None)
   return checkout_queryset.filter(token=token,  user=None).get_or_create(
       user =None
   )[0]


def set_checkout_cookie(checkout, response):
    max_age = int(timedelta(days=30).total_seconds())
    response.set_signed_cookie('checkout', checkout.token, max_age=max_age)

def add_product_to_checkout(request, pk):
    product = get_object_or_404(Product, pk= pk)
    if request.method == 'POST':
        checkout =  get_or_create_checkout(request)
        instance = CheckoutLine(product=product, checkout=checkout)
        form = CheckOutLineForm(request.POST, instance=instance, product=product)
        if form.is_valid():
            checkout_line = CheckoutLine.objects.filter(
                product = product,
                checkout = checkout
            )
            if checkout_line.exists():
                instance = checkout_line[0]
                instance.quantity += int(request.POST.get('quantity'))
                instance.save()
            else:
                form.save()
            return HttpResponseRedirect(reverse('checkout:checkout_index'))
        else:
            response = detail_product(request, product.slug, form)
        
        if not request.user.is_authenticated:
            set_checkout_cookie(checkout, response)
        return response
    return HttpResponseRedirect(reverse('checkout:checkout_index'))

product/templates/product/create.html
<form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>

product/templates/product/detail.html
{% extends 'base.html' %}


{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for image in object.productimage_set.all %}
        <div class="carousel-item 
        {% if forloop.counter0 == 0 %} active {% endif %}">
            <img src="{{image.image.url}}" class="d-block w-100" alt="{{image.alt}}">
        </div>
        {% endfor %}    
      
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
    <h1>{{object.name}}</h1>
    <p>price: {{object.price}}</p>
    <p>sku: {{object.sku}}</p>
    <p>description: {{object.weight}}</p>
    <p> weight: {{object.category}}</p>
    <p>stock: {{object.brand}}</p>
    <p>category: {{object.description}}</p>
    <form action="{% url 'products:add_product_to_checkout' pk=object.pk %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button class="btn btn-primary" type="submit">Add to cart</button>
    </form>
{% endblock content %}

    

product/templates/product/list.html
{% extends 'base.html' %}


{% block content %}

   {% for object in  object_list %}
   <div>
    <a href="{% url 'products:detail_product' slug=object.slug %}">
        <img src="{{ object.get_thumbnail.image.url}}" alt="{{ object.get_thumbnail.alt}}">
      <h5>
        {{object.name}}
      </h5>
      <p>{{object.sku}} |  {{object.price}} </p>
    </a>
     
   {% endfor %}
sss
   
   <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    
{% endblock content %}

    